### ISSUE TITLE
add option for FileType.AUDIO to *not* open apple music

### ISSUE THREAD

**Issue by thejacer87** [miguelpruivo/plugins_flutter_file_picker#112] opened 2019-07-22 07:29 UTC
I want my iOS users to be able to search the Files app for audio, not apple music files, to avoid DRM stuff.

problem with using .CUSTOM is I can't filter multiple extensions at once, at least until #68 is implemented.

so at the moment .ANY with custom handling on the app side is the only way. which seems more cumbersome than

basically this issue is moot if #68 is on the horizon, otherwise it would be nice if .AUDIO could have an option to open the files app on iOS

edit: also, excuse the ignorance, but if the audio files are DRM'd, what can one even do with it when picked in the file_picker?

**Comment by miguelpruivo** [comment] 2019-07-25 16:34
This is in a way a duplicate of #68. Please, use the #99 to upvote on features.

Thank you!

**Closed by miguelpruivo** 2019-07-25 16:34 UTC
Labels: suggestion
