### ISSUE TITLE
please fix this bug

### ISSUE THREAD

**Issue by timordu** [miguelpruivo/plugins_flutter_file_picker#120] opened 2019-08-01 08:21 UTC
I/FilePicker(24101): [SingleFilePick] File URI:content://com.huawei.hidisk.fileprovider/root/storage/emulated/0/Android/data/com.android.family_bill/files/family_bill.backup
E/FilePickerUtils(24101): Getting for API 19 or abovecontent://com.huawei.hidisk.fileprovider/root/storage/emulated/0/Android/data/com.android.family_bill/files/family_bill.backup
E/FilePickerUtils(24101): NO DOCUMENT URI - CONTENT
D/AndroidRuntime(24101): Shutting down VM
E/AndroidRuntime(24101): FATAL EXCEPTION: main
E/AndroidRuntime(24101): Process: com.android.family_bill, PID: 24101
E/AndroidRuntime(24101): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=37657, result=-1, data=Intent { dat=content://com.huawei.hidisk.fileprovider/root/storage/emulated/0/Android/data/com.android.family_bill/files/family_bill.backup flg=0x3 }} to activity {com.android.family_bill/com.android.family_bill.MainActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
E/AndroidRuntime(24101): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4932)
E/AndroidRuntime(24101): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4975)
E/AndroidRuntime(24101): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime(24101): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
E/AndroidRuntime(24101): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime(24101): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(24101): 	at android.app.ActivityThread.main(ActivityThread.java:7425)
E/AndroidRuntime(24101): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24101): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime(24101): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/AndroidRuntime(24101): Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
E/AndroidRuntime(24101): 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
E/AndroidRuntime(24101): 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
E/AndroidRuntime(24101): 	at com.mr.flutter.plugin.filepicker.FileUtils.getDataColumn(FileUtils.java:132)
E/AndroidRuntime(24101): 	at com.mr.flutter.plugin.filepicker.FileUtils.getForApi19(FileUtils.java:113)
E/AndroidRuntime(24101): 	at com.mr.flutter.plugin.filepicker.FileUtils.getPath(FileUtils.java:29)
E/AndroidRuntime(24101): 	at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult(FilePickerPlugin.java:81)
E/AndroidRuntime(24101): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime(24101): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime(24101): 	at io.flutter.app.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:137)
E/AndroidRuntime(24101): 	at android.app.Activity.dispatchActivityResult(Activity.java:7690)
E/AndroidRuntime(24101): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4928)
E/AndroidRuntime(24101): 	... 9 more

**Comment by miguelpruivo** [comment] 2019-08-01 08:49
Hi, how are you picking the file?  I need a few more details so I can help you.

Thank you.

**Comment by timordu** [comment] 2019-08-01 09:36
`File file = await FilePicker.getFile(type: FileType.ANY, fileExtension: 'backup');'

'String jsonStr = await file.readAsString();`

The above is my calling code. and  the phone is huawei nova youth (WAS-AL00),  android version is 8.0.0, emui version is 8.0.0 .

I wonder if the above information can help you.

**Comment by miguelpruivo** [comment] 2019-08-01 09:54
Would you mind to try on a different phone and see if still happens? (Or you can just drop the file in an emulator with version 8.0 and see if its working). 

Thank you.

**Comment by timordu** [comment] 2019-08-02 01:24
i try it on emulator and xiaomi mix 2s, it`s ok .  only on huawei nova youth report error,   maybe it's compatibility.

**Comment by miguelpruivo** [comment] 2019-08-02 01:38
@timordu, this are the kind of issues that are tough to follow, but I’ll try my best.

- Does the devices where it works fine, have the same android version?
- Did you use the exact same file?
- If the answers to the previous questions are both true, in the Huawei nova youth, does that happen with **_all_** files, or just that one?

Thank you.

**Comment by miguelpruivo** [comment] 2019-08-05 11:43
Bumping this @timordu.

**Comment by miguelpruivo** [comment] 2019-08-09 11:56
Closing since no further information was given. Feel free to reopen if the problem is still on. Thank you.

**Closed by miguelpruivo** 2019-08-09 11:56 UTC

**Comment by wreppun** [comment] 2019-08-22 00:22
I just got a similar StackTrace on a chromebook HP x360 `Android 7.1.1 (API 25)`:

```
I/FilePicker( 1542): Checking permission: android.permission.READ_EXTERNAL_STORAGE
D/ViewRootImpl[MainActivity]( 1542): Window focused:null
I/FilePicker( 1542): [SingleFilePick] File URI:content://org.chromium.arc.file_system.fileprovider/download/TheLearnerRevolution_EducationDesignLab.pdf
E/FilePickerUtils( 1542): Getting for API 19 or abovecontent://org.chromium.arc.file_system.fileprovider/download/TheLearnerRevolution_EducationDesignLab.pdf
E/FilePickerUtils( 1542): NO DOCUMENT URI - CONTENT
D/AndroidRuntime( 1542): Shutting down VM
E/AndroidRuntime( 1542): FATAL EXCEPTION: main
E/AndroidRuntime( 1542): Process: com.unrulr.unrulr, PID: 1542
E/AndroidRuntime( 1542): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=8351, result=-1, data=Intent { dat=content://org.chromium.arc.file_system.fileprovider/download/TheLearnerRevolution_EducationDesignLab.pdf flg=0x1 }} to activity {com.unrulr.unrulr/com.unrulr.unrulr.MainActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
E/AndroidRuntime( 1542):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4169)
E/AndroidRuntime( 1542):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4212)
E/AndroidRuntime( 1542):        at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime( 1542):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
E/AndroidRuntime( 1542):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1542):        at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 1542):        at android.app.ActivityThread.main(ActivityThread.java:6320)
E/AndroidRuntime( 1542):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1542):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
E/AndroidRuntime( 1542):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
E/AndroidRuntime( 1542): Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
E/AndroidRuntime( 1542):        at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
E/AndroidRuntime( 1542):        at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
E/AndroidRuntime( 1542):        at com.mr.flutter.plugin.filepicker.FileUtils.getDataColumn(FileUtils.java:132)
E/AndroidRuntime( 1542):        at com.mr.flutter.plugin.filepicker.FileUtils.getForApi19(FileUtils.java:113)
E/AndroidRuntime( 1542):        at com.mr.flutter.plugin.filepicker.FileUtils.getPath(FileUtils.java:29)
E/AndroidRuntime( 1542):        at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult(FilePickerPlugin.java:81)
E/AndroidRuntime( 1542):        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime( 1542):        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime( 1542):        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime( 1542):        at android.app.Activity.dispatchActivityResult(Activity.java:7038)
E/AndroidRuntime( 1542):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4165)
E/AndroidRuntime( 1542):        ... 9 more
Lost connection to device.
```

A quick google of the exception turned up this post on stackoverflow:
https://stackoverflow.com/questions/42508383/illegalargumentexception-column-data-does-not-exist/42508921

It recommends using a `ContentResolver -> InputStream` instead of a `ContentResolver -> Cursor`

**Comment by Gustavo0706** [comment] 2021-08-05 12:22
> I/FilePicker(24101): [SingleFilePick] File URI:content://com.huawei.hidisk.fileprovider/root/storage/emulated/0/Android/data/com.android.family_bill/files/family_bill.backup
> E/FilePickerUtils(24101): Getting for API 19 or abovecontent://com.huawei.hidisk.fileprovider/root/storage/emulated/0/Android/data/com.android.family_bill/files/family_bill.backup
> E/FilePickerUtils(24101): NO DOCUMENT URI - CONTENT
> D/AndroidRuntime(24101): Shutting down VM
> E/AndroidRuntime(24101): FATAL EXCEPTION: main
> E/AndroidRuntime(24101): Process: com.android.family_bill, PID: 24101
> E/AndroidRuntime(24101): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=37657, result=-1, data=Intent { dat=content://com.huawei.hidisk.fileprovider/root/storage/emulated/0/Android/data/com.android.family_bill/files/family_bill.backup flg=0x3 }} to activity {com.android.family_bill/com.android.family_bill.MainActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
> E/AndroidRuntime(24101): at android.app.ActivityThread.deliverResults(ActivityThread.java:4932)
> E/AndroidRuntime(24101): at android.app.ActivityThread.handleSendResult(ActivityThread.java:4975)
> E/AndroidRuntime(24101): at android.app.ActivityThread.-wrap20(Unknown Source:0)
> E/AndroidRuntime(24101): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
> E/AndroidRuntime(24101): at android.os.Handler.dispatchMessage(Handler.java:108)
> E/AndroidRuntime(24101): at android.os.Looper.loop(Looper.java:166)
> E/AndroidRuntime(24101): at android.app.ActivityThread.main(ActivityThread.java:7425)
> E/AndroidRuntime(24101): at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(24101): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
> E/AndroidRuntime(24101): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
> E/AndroidRuntime(24101): Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
> E/AndroidRuntime(24101): at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
> E/AndroidRuntime(24101): at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
> E/AndroidRuntime(24101): at com.mr.flutter.plugin.filepicker.FileUtils.getDataColumn(FileUtils.java:132)
> E/AndroidRuntime(24101): at com.mr.flutter.plugin.filepicker.FileUtils.getForApi19(FileUtils.java:113)
> E/AndroidRuntime(24101): at com.mr.flutter.plugin.filepicker.FileUtils.getPath(FileUtils.java:29)
> E/AndroidRuntime(24101): at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult(FilePickerPlugin.java:81)
> E/AndroidRuntime(24101): at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
> E/AndroidRuntime(24101): at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
> E/AndroidRuntime(24101): at io.flutter.app.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:137)
> E/AndroidRuntime(24101): at android.app.Activity.dispatchActivityResult(Activity.java:7690)
> E/AndroidRuntime(24101): at android.app.ActivityThread.deliverResults(ActivityThread.java:4928)
> E/AndroidRuntime(24101): ... 9 more
