### ISSUE TITLE
Fails under VS Code 

### ISSUE THREAD

**Issue by roidy** [miguelpruivo/plugins_flutter_file_picker#81] opened 2019-05-15 13:28 UTC
Fails under VS Code complaining about AndroidX. My code works perfectly when file_picker is remover from pubspec.yaml

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale en-GB)
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Android Studio (version 3.1)
> [√] VS Code (version 1.33.1)
> [√] Connected device (1 available)

> Launching lib\main.dart on F5321 in debug mode...
> D8: Program type already present: android.support.v4.os.ResultReceiver$1
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> 
> > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\4.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\5.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\6.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\7.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\8.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\9.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\10.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\11.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\12.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\13.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\14.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\15.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\16.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\17.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\18.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\19.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\20.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\21.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\22.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\23.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\24.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\25.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\26.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\27.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\28.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\29.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\30.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\31.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\32.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\33.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\34.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\35.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\36.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\37.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\38.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\39.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\40.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\41.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\42.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\43.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\44.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\45.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\46.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\47.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\48.jar, F:\flutter-projects\tvmaze\build\app\intermediates\transforms\dexBuilder\debug\49.jar
> 
>   Program type already present: android.support.v4.os.ResultReceiver$1
>   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 17s
> *******************************************************************************************
> The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
> See https://goo.gl/CP92wY for more information on the problem and how to fix it.
> *******************************************************************************************
> Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)
> 
> 
>

**Comment by miguelpruivo** [comment] 2019-05-15 13:32
H. @roidy, this kind of bug is usually related to project dependencies or conflicts between them, otherwise it wouldn't build for any other user. Using the VS Code shouldn't have any impact, it's just the build process.

Can you show me your `android/app/build.gradle` file? Also, can you try to run the package's example app and see if it builds for you?

**Comment by roidy** [comment] 2019-05-15 13:40
I've narrowed the fail down to also including simple_permissions: ^0.1.9 in pubspec.yaml

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.tvmaze"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```

**Comment by miguelpruivo** [comment] 2019-05-15 15:16
This line likely explains where the problem is:

`Program type already present: android.support.v4.os.ResultReceiver$1`

**Comment by roidy** [comment] 2019-05-15 17:25
Yes, I saw that as well. So is there a fix?

**Comment by miguelpruivo** [comment] 2019-05-15 18:15
No problem, I was going to suggest to check your `gradle.properties` file and make sure that you have these two lines below there:
```
android.useAndroidX=true
android.enableJetifier=true
```
Anyway, since you've found a solution, I'm going to close this. Feel free to reopen if you still find any issue related to this.

**Closed by miguelpruivo** 2019-05-15 18:15 UTC
